### ISSUE TITLE
Master-Refactor merge aftermath

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi#280]
- [ ] flecsi-sp broken: laristra/flecsi-sp#9
- [ ] only legion backend works: #279
- [x] `Werror` clang builds broken: #278 
- [x] 8 tests fail on Travis: #269

**Comment by ollielo** [comment]
Should be fixed with PR 308.

**Comment by junghans** [comment]
laristra/flecsi-sp#9 as well?

**Comment by junghans** [comment]
flecsi-sp still broken:
https://travis-ci.org/laristra/flecsi-sp/builds/268438605
